import styles from './Footer.module.css';

function Footer() {
  return (
    <footer className={styles.footer}>
      <div>
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
      </div>
      <div>
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
      </div>
      <div>
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
        <br />
        ...
      </div>
    </footer>
  );
}

export default Footer;
